#!/usr/bin/python
## Build script
## inst_i denotes ith instruction
## if inst_i==0 than instruction is successful else not

# Apache Server Stop  
import os
inst_1=os.system("service apache2 stop")

if(inst_1==0):
	print "********************"
	print "Shutdown Successful"
	print "********************"
else:
	print "*********************"
	print "Shutdown Unsuccessful"
	print "*********************"
